### ISSUE TITLE
type error: moment(...).utcOffset(...).format is not a function

### ISSUE THREAD

**Issue by vladciphersky** [vimestats/backend-api#4]
![image](https://user-images.githubusercontent.com/32297717/69473445-5943cf00-0dd6-11ea-8e64-2be1983da743.png)
![image](https://user-images.githubusercontent.com/32297717/69473446-61037380-0dd6-11ea-8dae-6367637f6bad.png)

**Comment by runic-tears** [comment]
@vladciphersky какая версия Node, какая версия OS?

**Comment by vladciphersky** [comment]
> @vladciphersky какая версия Node, какая версия OS?

Welcome to Ubuntu 14.04.6 LTS
node -v === v12.13.0

**Comment by runic-tears** [comment]
@vladciphersky как запускаешь сервер? Через `npm start` или `node`? Что именно нужно сделать, чтобы я мог воспороизвести?

**Comment by runic-tears** [comment]
Мне не удалось воспроизвести баг.

**Мои шаги**
1. Выполнен запрос GET к `/vk/` (возвращено 404)
2. Выполнен запрос GET к `/vk/demotions` (возвращено 200)

**Система**
- Ubuntu 18.04 LTS
- Node 13.2.0

**Comment by vladciphersky** [comment]
> @vladciphersky как запускаешь сервер? Через `npm start` или `node`? Что именно нужно сделать, чтобы я мог воспороизвести?

Из корня папки:
$ node src/app.js

**Comment by runic-tears** [comment]
@vladciphersky попробуй удалить node_modules и выполни `npm install`, далее запусти через `npm start`

**Comment by vladciphersky** [comment]
> @vladciphersky попробуй удалить node_modules и выполни `npm install`, далее запусти через `npm start`

Удалил, npm install, npm start, та же ошибка.

**Comment by runic-tears** [comment]
@vladciphersky попробуй обновить Node до версии 13.2.0, возможно, что-то не так с библиотекой или зависимости этой библиотеки требуют более новую версию

**Comment by vladciphersky** [comment]
> @vladciphersky попробуй обновить Node до версии 13.2.0, возможно, что-то не так с библиотекой или зависимости этой библиотеки требуют более новую версию

![image](https://user-images.githubusercontent.com/32297717/69474843-aed4a780-0de7-11ea-8b60-e39f06a898c3.png)
После установки сразу обновил нпм, и переустановил либы снова. Не помогает :man_shrugging:

**Comment by vladciphersky** [comment]
Позор мне, додику. Проблема была в том, что не установлен параметр TIMEZONE_OFFSET в конфигурации :person_facepalming:
Всё снова работает.
![image](https://user-images.githubusercontent.com/32297717/69474871-34f0ee00-0de8-11ea-98e2-173ee5ca7fde.png)
